name: Deploy React App

on:
  push:
    branches:
      - master  # Change this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js and Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y git-ssh
          npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: build/
          target: /home/simpleinc-darshanparmar/htdocs/darshanparmar.simpleinc.in/


