name: Deploy React App

on:
  push:
    branches:
      - master  # Change this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust Node.js version as needed

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to VPS
        uses: easingthemes/ssh-deploy@v2
        with:
          server_ip: ${{ secrets.SSH_HOST }}  # Add your VPS server's IP address or domain name as a secret
          server_username: ${{ secrets.SSH_USERNAME }}  # Add your VPS server's username as a secret
          server_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your VPS server's SSH private key as a secret
          local_path: $GITHUB_WORKSPACE/build/  # Path to your React app's build directory
          remote_path: /htdocs/darshanparmar.simpleinc.in/  # Path on your VPS server where the app should be deployed
          REMOTE_PORT: 22  # Port for SSH connection, adjust if needed
          TARGET: /home/simpleinc-darshanparmar/  # Adjust the target directory on the remote server
          ARGS: -rltgoDzvO
