name: Deploy React App

on:
  push:
    branches:
      - master  # Change this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust Node.js version as needed

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Check SSH Connection and Remote Path
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'if [ ! -d /home/simpleinc-darshanparmar/htdocs/darshanparmar.simpleinc.in ]; then echo "Remote path does not exist"; exit 1; fi'

      - name: Deploy to VPS
        run: |
          scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no $GITHUB_WORKSPACE/build/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/simpleinc-darshanparmar/htdocs/darshanparmar.simpleinc.in/
