name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Debug
        run: |
          ls -la $GITHUB_WORKSPACE/build

      - name: Copy folder content recursively to VPS
        uses: garygrossgarten/github-action-scp@release
        with:
          local: $GITHUB_WORKSPACE/build
          remote: /home/simpleinc-darshanparmar/htdocs/darshanparmar.simpleinc.in/
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
