name: Deploy React App

on:
  push:
    branches:
      - master  # Change to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Clean remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Remove everything in the target folder to ensure a clean slate
            rm -rf /home/simpleinc-darshanparmar/htdocs/darshanparmar.simpleinc.in/*

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          # Upload "build" directory but strip out the top-level "build" folder
          source: 'build'
          target: '/home/simpleinc-darshanparmar/htdocs/darshanparmar.simpleinc.in/'
          strip_components: 1
